# Generated by Django 5.2.7 on 2025-11-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
