# Generated by Django 5.2.7 on 2025-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_seller_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="seller_profiles/"
            ),
        ),
    ]
