# Generated by Django 5.2.7 on 2025-11-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antiques", "0002_wishlist"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antique",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="antiques",
                to="sellers.seller",
            ),
        ),
    ]
