# Generated by Django 5.2.7 on 2025-11-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("antiques", "0003_antique_seller"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="antique",
            name="antiques_an_short_i_df05a0_idx",
        ),
        migrations.RemoveField(
            model_name="antique",
            name="short_id",
        ),
    ]
