# Generated by Django 5.2.7 on 2025-11-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_seller"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seller",
        ),
    ]
